#!/bin/bash
# Установка и настройка coturn на VPS для TURN (видеозвонки).
# Запуск на сервере: cd /var/www/messager && bash scripts/setup-coturn.sh
# Опционально: EXTERNAL_IP=1.2.3.4 MESSAGER_ROOT=/var/www/messager bash scripts/setup-coturn.sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

EXTERNAL_IP="${EXTERNAL_IP:-89.169.39.244}"
MESSAGER_ROOT="${MESSAGER_ROOT:-/var/www/messager}"
FRONTEND_DIR="$MESSAGER_ROOT/frontend-web"

echo -e "${GREEN}=== Setup coturn (TURN for WebRTC) ===${NC}"

# 1) Установка coturn
if command -v apt-get >/dev/null 2>&1; then
  echo -e "${YELLOW}[1/7] Installing coturn (apt)...${NC}"
  apt-get update -qq
  apt-get install -y coturn
elif command -v yum >/dev/null 2>&1; then
  echo -e "${YELLOW}[1/7] Installing coturn (yum)...${NC}"
  yum install -y epel-release 2>/dev/null || true
  yum install -y coturn
else
  echo -e "${RED}Cannot install coturn: no apt or yum. Install coturn manually.${NC}"
  exit 1
fi

# 2) Включить сервис
echo -e "${YELLOW}[2/7] Enabling coturn service...${NC}"
if [ -f /etc/default/coturn ]; then
  sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn 2>/dev/null || true
fi
systemctl enable coturn 2>/dev/null || true

# 3) Генерация учётных данных для TURN
TURN_USER="turn_$(openssl rand -hex 4)"
TURN_PASS="$(openssl rand -base64 16 | tr -d '/+=' | head -c 20)"
echo -e "${GREEN}TURN user: $TURN_USER${NC}"
echo -e "${GREEN}TURN pass: (saved to .env.production)${NC}"

# 4) Конфиг coturn
TURN_CONF=""
if [ -f /etc/coturn/turnserver.conf ]; then
  TURN_CONF=/etc/coturn/turnserver.conf
elif [ -f /etc/turnserver.conf ]; then
  TURN_CONF=/etc/turnserver.conf
else
  TURN_CONF=/etc/turnserver.conf
fi

echo -e "${YELLOW}[3/7] Writing $TURN_CONF...${NC}"
mkdir -p "$(dirname "$TURN_CONF")"
[ -f "$TURN_CONF" ] && cp "$TURN_CONF" "${TURN_CONF}.bak" 2>/dev/null || true

cat > "$TURN_CONF" << EOF
# Generated by scripts/setup-coturn.sh
listening-ip=0.0.0.0
relay-ip=0.0.0.0
listening-port=3478
tls-listening-port=5349
external-ip=$EXTERNAL_IP
realm=neekloai.ru
lt-cred-mech
user=$TURN_USER:$TURN_PASS
log-file=/var/log/turnserver/turnserver.log
verbose
EOF

# 5) Логи и права
echo -e "${YELLOW}[4/7] Creating log dir...${NC}"
mkdir -p /var/log/turnserver
chown turnserver:turnserver /var/log/turnserver 2>/dev/null || chown nobody:nogroup /var/log/turnserver 2>/dev/null || true

# 6) Файрвол
echo -e "${YELLOW}[5/7] Opening firewall ports 3478, 49152-65535/udp...${NC}"
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q 'Status:'; then
  ufw allow 3478/udp
  ufw allow 3478/tcp
  ufw allow 49152:65535/udp
  ufw reload 2>/dev/null || true
elif command -v firewall-cmd >/dev/null 2>&1; then
  firewall-cmd --permanent --add-port=3478/udp
  firewall-cmd --permanent --add-port=3478/tcp
  firewall-cmd --permanent --add-port=49152-65535/udp
  firewall-cmd --reload
else
  echo -e "${YELLOW}No ufw/firewalld found. Open ports 3478 (udp/tcp) and 49152-65535/udp manually.${NC}"
fi

# 7) Запуск coturn
echo -e "${YELLOW}[6/7] Starting coturn...${NC}"
systemctl restart coturn
sleep 1
if systemctl is-active --quiet coturn; then
  echo -e "${GREEN}coturn is running.${NC}"
else
  echo -e "${RED}coturn failed to start. Check: journalctl -u coturn -n 30${NC}"
  exit 1
fi

# 8) .env.production для фронта
echo -e "${YELLOW}[7/7] Writing $FRONTEND_DIR/.env.production...${NC}"
if [ ! -d "$FRONTEND_DIR" ]; then
  echo -e "${RED}Frontend dir not found: $FRONTEND_DIR${NC}"
  exit 1
fi
cat > "$FRONTEND_DIR/.env.production" << ENVEOF
# TURN for WebRTC (generated by setup-coturn.sh)
VITE_TURN_URL=turn:${EXTERNAL_IP}:3478
VITE_TURN_USER=$TURN_USER
VITE_TURN_CREDENTIAL=$TURN_PASS
ENVEOF
chmod 600 "$FRONTEND_DIR/.env.production"
echo -e "${GREEN}.env.production created. Do not commit (contains secrets).${NC}"

echo ""
echo -e "${GREEN}=== Done ===${NC}"
echo "Next: rebuild frontend and deploy: cd $MESSAGER_ROOT && bash scripts/pull-and-update.sh"
echo "Or: cd $FRONTEND_DIR && npm run build"
